---
- name: Deploy and Configure Nginx as a Reverse Proxy
  hosts: vm1
  become: yes
  remote_user: ubuntu

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx as Reverse Proxy
      copy:
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://10.150.190.191:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        dest: /etc/nginx/sites-available/reverse_proxy
      notify: Restart Nginx

    - name: Enable Reverse Proxy Configuration
      file:
        src: /etc/nginx/sites-available/reverse_proxy
        dest: /etc/nginx/sites-enabled/reverse_proxy
        state: link
      notify: Restart Nginx

    - name: Remove Default Nginx Configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

