---
- name: Deploy Simple RESTful Flask Application with MySQL Connection
  hosts: vm2
  become: yes
  remote_user: ubuntu

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - libmysqlclient-dev
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: /opt/flask_app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create Flask application
      copy:
        content: |
          from flask import Flask, jsonify
          import mysql.connector

          app = Flask(__name__)

          def get_db_connection():
              try:
                  conn = mysql.connector.connect(
                      host="10.150.190.192",
                      user="username",
                      password="password",
                      database="name"
                  )
                  conn.close()
                  return True
              except mysql.connector.Error:
                  return False

          @app.route("/", methods=["GET"])
          def home():
              return jsonify({"message": "Hello World"})

          @app.route("/db", methods=["GET"])
          def check_db():
              if get_db_connection():
                  return jsonify({"message": "Connection OK"})
              else:
                  return jsonify({"message": "Connection Failed"}), 500

          if __name__ == "__main__":
              app.run(host="0.0.0.0", port=5000)
        dest: /opt/flask_app/app.py
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Create virtual environment and install dependencies
      shell: |
        python3 -m venv /opt/flask_app/venv
        /opt/flask_app/venv/bin/pip install flask mysql-connector-python
      args:
        creates: /opt/flask_app/venv

    - name: Create systemd service for Flask app
      copy:
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/opt/flask_app
          ExecStart=/opt/flask_app/venv/bin/python /opt/flask_app/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flask_app.service
        mode: '0644'

    - name: Reload systemd and enable Flask service
      systemd:
        daemon_reload: yes
        name: flask_app
        enabled: yes
        state: started

